In [47]:
import dask.dataframe as daskdf
import dask.array as da
import pandas as pd

# randomly generate dask array

In [37]:
x = da.random.random((10, 5), chunks=(2, 2)) # 10 by 5 array, partitioned into 2 by 2

In [38]:
x.compute()

array([[0.99629746, 0.16409777, 0.22680353, 0.75350057, 0.939182  ],
       [0.87918309, 0.43229732, 0.98222631, 0.54707305, 0.32218534],
       [0.17705935, 0.32080152, 0.63076997, 0.91587806, 0.11711293],
       [0.89760352, 0.4182951 , 0.34324663, 0.63590565, 0.65903146],
       [0.86656831, 0.66955252, 0.77308568, 0.44463939, 0.2252608 ],
       [0.69912354, 0.77240168, 0.55381344, 0.83582001, 0.68247869],
       [0.72775312, 0.40648311, 0.63605874, 0.16287378, 0.75578071],
       [0.85774255, 0.54591585, 0.01802349, 0.94643708, 0.56647888],
       [0.8812822 , 0.83325071, 0.47076871, 0.56122592, 0.4935374 ],
       [0.33726477, 0.50274395, 0.57507604, 0.91988615, 0.4666092 ]])

# dask dataframe and pandas

In [43]:
panda = pd.DataFrame(x.compute())
panda

0         1         2         3         4
0  0.996297  0.164098  0.226804  0.753501  0.939182
1  0.879183  0.432297  0.982226  0.547073  0.322185
2  0.177059  0.320802  0.630770  0.915878  0.117113
3  0.897604  0.418295  0.343247  0.635906  0.659031
4  0.866568  0.669553  0.773086  0.444639  0.225261
5  0.699124  0.772402  0.553813  0.835820  0.682479
6  0.727753  0.406483  0.636059  0.162874  0.755781
7  0.857743  0.545916  0.018023  0.946437  0.566479
8  0.881282  0.833251  0.470769  0.561226  0.493537
9  0.337265  0.502744  0.575076  0.919886  0.466609

In [49]:
df = daskdf.from_pandas(panda, npartitions=2)
df

Dask DataFrame Structure:
                     0        1        2        3        4
npartitions=2                                             
0              float64  float64  float64  float64  float64
5                  ...      ...      ...      ...      ...
9                  ...      ...      ...      ...      ...
Dask Name: from_pandas, 2 tasks

In [52]:
df.compute()

0         1         2         3         4
0  0.996297  0.164098  0.226804  0.753501  0.939182
1  0.879183  0.432297  0.982226  0.547073  0.322185
2  0.177059  0.320802  0.630770  0.915878  0.117113
3  0.897604  0.418295  0.343247  0.635906  0.659031
4  0.866568  0.669553  0.773086  0.444639  0.225261
5  0.699124  0.772402  0.553813  0.835820  0.682479
6  0.727753  0.406483  0.636059  0.162874  0.755781
7  0.857743  0.545916  0.018023  0.946437  0.566479
8  0.881282  0.833251  0.470769  0.561226  0.493537
9  0.337265  0.502744  0.575076  0.919886  0.466609

# dask dataframe to dask array

In [55]:
df.to_dask_array().compute()

array([[0.99629746, 0.16409777, 0.22680353, 0.75350057, 0.939182  ],
       [0.87918309, 0.43229732, 0.98222631, 0.54707305, 0.32218534],
       [0.17705935, 0.32080152, 0.63076997, 0.91587806, 0.11711293],
       [0.89760352, 0.4182951 , 0.34324663, 0.63590565, 0.65903146],
       [0.86656831, 0.66955252, 0.77308568, 0.44463939, 0.2252608 ],
       [0.69912354, 0.77240168, 0.55381344, 0.83582001, 0.68247869],
       [0.72775312, 0.40648311, 0.63605874, 0.16287378, 0.75578071],
       [0.85774255, 0.54591585, 0.01802349, 0.94643708, 0.56647888],
       [0.8812822 , 0.83325071, 0.47076871, 0.56122592, 0.4935374 ],
       [0.33726477, 0.50274395, 0.57507604, 0.91988615, 0.4666092 ]])

In [59]:
# return chunk-size of dask array
df.to_dask_array(lengths=True)

dask.array<array, shape=(10, 5), dtype=float64, chunksize=(5, 5)>

In [58]:
# alt method
df.values.compute()

array([[0.99629746, 0.16409777, 0.22680353, 0.75350057, 0.939182  ],
       [0.87918309, 0.43229732, 0.98222631, 0.54707305, 0.32218534],
       [0.17705935, 0.32080152, 0.63076997, 0.91587806, 0.11711293],
       [0.89760352, 0.4182951 , 0.34324663, 0.63590565, 0.65903146],
       [0.86656831, 0.66955252, 0.77308568, 0.44463939, 0.2252608 ],
       [0.69912354, 0.77240168, 0.55381344, 0.83582001, 0.68247869],
       [0.72775312, 0.40648311, 0.63605874, 0.16287378, 0.75578071],
       [0.85774255, 0.54591585, 0.01802349, 0.94643708, 0.56647888],
       [0.8812822 , 0.83325071, 0.47076871, 0.56122592, 0.4935374 ],
       [0.33726477, 0.50274395, 0.57507604, 0.91988615, 0.4666092 ]])

# sparse arrays

In [62]:
import sparse

In [66]:
xx = x.compute()

In [67]:
xx[xx < 0.80] = 0

In [68]:
xx

array([[0.99629746, 0.        , 0.        , 0.        , 0.939182  ],
       [0.87918309, 0.        , 0.98222631, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.91587806, 0.        ],
       [0.89760352, 0.        , 0.        , 0.        , 0.        ],
       [0.86656831, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.83582001, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.85774255, 0.        , 0.        , 0.94643708, 0.        ],
       [0.8812822 , 0.83325071, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.91988615, 0.        ]])

In [71]:
xxd = da.from_array(xx, chunks=(2, 2))

In [72]:
s = xxd.map_blocks(sparse.COO)

In [77]:
s.sum(axis=0)[0:10].compute()  # computes the sum of each column

<COO: shape=(5,), dtype=float64, nnz=5, fill_value=0.0>

In [78]:
_.todense()

array([5.37867712, 0.83325071, 0.98222631, 3.6180213 , 0.939182  ])

# Stats

In [79]:
from dask.array import stats

In [80]:
x = da.random.beta(1, 1, size=(1000,), chunks=10)
k, s, m = [stats.kurtosis(x), stats.skew(x), stats.moment(x, 5)]
dask.compute(k, s, m)

(array(1.79911803), array(0.02079301), 0.0002198304752702045)

In [81]:
# Statistical test

In [82]:
a = da.random.uniform(size=(50,), chunks=(25,))
b = a + da.random.uniform(low=-0.15, high=0.15, size=(50,), chunks=(25,))
result = stats.ttest_rel(a, b)
result.compute()

Ttest_relResult(statistic=1.2854467581843538, pvalue=0.20467856724449054)

# Stacking

In [87]:
import dask.array as da
import numpy as np

In [91]:
a = np.zeros((3, 4))
b = np.ones((3, 4))

In [93]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
arr0 = da.from_array(a, chunks=(1, 2))
arr1 = da.from_array(b, chunks=(1, 2))

In [85]:
data = [arr0, arr1]

In [86]:
# stack axis 1
x = da.stack(data, axis=0)
x.shape

(2, 3, 4)

In [95]:
# stack axis 2
x2 = da.stack(data, axis=1)
x2.shape

(3, 2, 4)

# Concatenate dask array

In [96]:
x = da.concatenate(data, axis=0)
x.shape

(6, 4)

In [98]:
x2 = da.concatenate(data, axis=1)
x2.shape

(3, 8)

# Blocks 

In [99]:
data = [
    [arr0, arr1],
    [arr1, arr0]
]

In [100]:
x = da.block(data)
x.shape

(6, 8)